apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 2  # Number of replicas for the Python app deployment
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: ronn4/app-image:last  # Replace with your actual Python app image
        ports:
        - containerPort: 8443  # Assuming your Python app runs on port 5000
        env:
        - name: ENV_VARIABLE_NAME
          value: "some-value"  # Replace with any environment variables needed
      imagePullSecrets:
      - name: regcred
